"""phase2_complete_schema

Revision ID: d19ddee7d36d
Revises: 
Create Date: 2026-08-28 17:33:16.322153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19ddee7d36d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('target_skill_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_id'), ['id'], unique=False)

    op.create_table('learning_resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('career_relevance', sa.JSON(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_model_version', sa.String(length=50), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('estimated_hours > 0', name='chk_positive_estimated_hours'),
    sa.CheckConstraint('quality_score >= 0.0 AND quality_score <= 1.0', name='chk_quality_score_range'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_resources_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_resources_slug'), ['slug'], unique=True)

    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('difficulty_tier', sa.String(length=50), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_skills_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('assessment_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('question_text', sa.String(length=500), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_option_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.String(length=500), nullable=True),
    sa.Column('difficulty_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_questions_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_questions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_questions_skill_id'), ['skill_id'], unique=False)

    op.create_table('learner_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('field_of_study', sa.String(length=100), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('weekly_hours', sa.Integer(), nullable=True),
    sa.Column('preferred_formats', sa.JSON(), nullable=True),
    sa.Column('learning_objective', sa.String(length=100), nullable=True),
    sa.Column('skill_confidence_map', sa.JSON(), nullable=True),
    sa.Column('velocity_score', sa.Float(), nullable=True),
    sa.Column('difficulty_tolerance', sa.Float(), nullable=True),
    sa.Column('state_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learner_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learner_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learner_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('resource_prerequisites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'skill_id', name='uq_resource_prerequisite')
    )
    with op.batch_alter_table('resource_prerequisites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_prerequisites_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_prerequisites_skill_id'), ['skill_id'], unique=False)

    op.create_table('resource_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('relevance_weight', sa.Float(), nullable=True),
    sa.Column('coverage_level', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.CheckConstraint('relevance_weight >= 0.0 AND relevance_weight <= 1.0', name='chk_resource_skill_relevance'),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'skill_id', name='uq_resource_skill')
    )
    with op.batch_alter_table('resource_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_skills_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_skills_skill_id'), ['skill_id'], unique=False)

    op.create_table('skill_prerequisites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('prerequisite_skill_id', sa.String(length=36), nullable=False),
    sa.Column('prerequisite_type', sa.String(length=50), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('skill_id != prerequisite_skill_id', name='chk_no_self_prerequisite'),
    sa.ForeignKeyConstraint(['prerequisite_skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'prerequisite_skill_id', name='uq_skill_prerequisite')
    )
    with op.batch_alter_table('skill_prerequisites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_prerequisites_prerequisite_skill_id'), ['prerequisite_skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_prerequisites_skill_id'), ['skill_id'], unique=False)

    op.create_table('assessment_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('selected_option_index', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('confidence_delta', sa.Float(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_responses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_responses_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_responses_question_id'), ['question_id'], unique=False)

    op.create_table('feedback_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_records_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_records_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_records_resource_id'), ['resource_id'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('target_role', sa.String(length=100), nullable=False),
    sa.Column('target_skills', sa.JSON(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_profile_id'), ['profile_id'], unique=False)

    op.create_table('interaction_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interaction_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interaction_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interaction_logs_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interaction_logs_resource_id'), ['resource_id'], unique=False)

    op.create_table('learner_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('self_rating', sa.String(length=50), nullable=True),
    sa.Column('assessed_confidence', sa.Float(), nullable=True),
    sa.Column('target_confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('last_assessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('assessed_confidence >= 0.0 AND assessed_confidence <= 1.0', name='chk_confidence_range'),
    sa.CheckConstraint('target_confidence >= 0.0 AND target_confidence <= 1.0', name='chk_target_confidence_range'),
    sa.ForeignKeyConstraint(['profile_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'skill_id', name='uq_learner_skill')
    )
    with op.batch_alter_table('learner_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learner_skills_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learner_skills_skill_id'), ['skill_id'], unique=False)

    op.create_table('progress_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_records_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_records_resource_id'), ['resource_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=True),
    sa.Column('embedding_model_version', sa.String(length=50), nullable=True),
    sa.Column('recommendation_state_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_recommendation_state_fingerprint'), ['recommendation_state_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_resource_id'), ['resource_id'], unique=False)

    op.create_table('learning_paths',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('algorithm_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_paths_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_paths_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_paths_profile_id'), ['profile_id'], unique=False)

    op.create_table('learning_path_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('learning_path_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('version_hash', sa.String(length=64), nullable=True),
    sa.Column('trigger', sa.String(length=100), nullable=True),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_path_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_path_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_path_versions_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_path_versions_learning_path_id'), ['learning_path_id'], unique=False)

    op.create_table('learning_path_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=True),
    sa.Column('phase_name', sa.String(length=100), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('planned_hours', sa.Float(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_skipped', sa.Boolean(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['learning_path_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_path_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_path_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_path_items_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_path_items_version_id'), ['version_id'], unique=False)

    op.create_table('roadmap_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('learning_path_id', sa.String(length=36), nullable=True),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('previous_version_id', sa.String(length=36), nullable=True),
    sa.Column('new_version_id', sa.String(length=36), nullable=True),
    sa.Column('previous_item_id', sa.String(length=36), nullable=True),
    sa.Column('new_item_id', sa.String(length=36), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('trigger', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['learning_path_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmap_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmap_changes_learning_path_id'), ['learning_path_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roadmap_changes_version_id'), ['version_id'], unique=False)

    op.create_table('recommendation_explanations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('path_item_id', sa.String(length=36), nullable=False),
    sa.Column('goal_relevance_score', sa.Float(), nullable=True),
    sa.Column('skill_gap_score', sa.Float(), nullable=True),
    sa.Column('prereq_score', sa.Float(), nullable=True),
    sa.Column('difficulty_score', sa.Float(), nullable=True),
    sa.Column('pref_score', sa.Float(), nullable=True),
    sa.Column('time_score', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('diversity_score', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('structured_reasons', sa.JSON(), nullable=True),
    sa.Column('human_readable_explanation', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['path_item_id'], ['learning_path_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_explanations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_explanations_path_item_id'), ['path_item_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_explanations_path_item_id'))

    op.drop_table('recommendation_explanations')
    with op.batch_alter_table('roadmap_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_changes_version_id'))
        batch_op.drop_index(batch_op.f('ix_roadmap_changes_learning_path_id'))

    op.drop_table('roadmap_changes')
    with op.batch_alter_table('learning_path_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_path_items_version_id'))
        batch_op.drop_index(batch_op.f('ix_learning_path_items_resource_id'))
        batch_op.drop_index(batch_op.f('ix_learning_path_items_id'))

    op.drop_table('learning_path_items')
    with op.batch_alter_table('learning_path_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_path_versions_learning_path_id'))
        batch_op.drop_index(batch_op.f('ix_learning_path_versions_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_learning_path_versions_id'))

    op.drop_table('learning_path_versions')
    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_paths_profile_id'))
        batch_op.drop_index(batch_op.f('ix_learning_paths_id'))
        batch_op.drop_index(batch_op.f('ix_learning_paths_goal_id'))

    op.drop_table('learning_paths')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_resource_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_recommendation_state_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_recommendations_profile_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_created_at'))

    op.drop_table('recommendations')
    with op.batch_alter_table('progress_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_records_resource_id'))
        batch_op.drop_index(batch_op.f('ix_progress_records_profile_id'))
        batch_op.drop_index(batch_op.f('ix_progress_records_id'))

    op.drop_table('progress_records')
    with op.batch_alter_table('learner_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learner_skills_skill_id'))
        batch_op.drop_index(batch_op.f('ix_learner_skills_profile_id'))

    op.drop_table('learner_skills')
    with op.batch_alter_table('interaction_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interaction_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_interaction_logs_profile_id'))
        batch_op.drop_index(batch_op.f('ix_interaction_logs_id'))

    op.drop_table('interaction_logs')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_profile_id'))
        batch_op.drop_index(batch_op.f('ix_goals_id'))

    op.drop_table('goals')
    with op.batch_alter_table('feedback_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_records_resource_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_records_profile_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_records_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_feedback_records_id'))

    op.drop_table('feedback_records')
    with op.batch_alter_table('assessment_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_responses_question_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_responses_profile_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_responses_id'))

    op.drop_table('assessment_responses')
    with op.batch_alter_table('skill_prerequisites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_prerequisites_skill_id'))
        batch_op.drop_index(batch_op.f('ix_skill_prerequisites_prerequisite_skill_id'))

    op.drop_table('skill_prerequisites')
    with op.batch_alter_table('resource_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_skills_skill_id'))
        batch_op.drop_index(batch_op.f('ix_resource_skills_resource_id'))

    op.drop_table('resource_skills')
    with op.batch_alter_table('resource_prerequisites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_prerequisites_skill_id'))
        batch_op.drop_index(batch_op.f('ix_resource_prerequisites_resource_id'))

    op.drop_table('resource_prerequisites')
    with op.batch_alter_table('learner_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learner_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_learner_profiles_id'))

    op.drop_table('learner_profiles')
    with op.batch_alter_table('assessment_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_questions_skill_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_questions_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_questions_assessment_id'))

    op.drop_table('assessment_questions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_slug'))
        batch_op.drop_index(batch_op.f('ix_skills_name'))
        batch_op.drop_index(batch_op.f('ix_skills_id'))
        batch_op.drop_index(batch_op.f('ix_skills_category'))

    op.drop_table('skills')
    with op.batch_alter_table('learning_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_resources_slug'))
        batch_op.drop_index(batch_op.f('ix_learning_resources_id'))

    op.drop_table('learning_resources')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_id'))

    op.drop_table('assessments')
    # ### end Alembic commands ###
