from typing import List, Dict, Any

CURATED_OPPORTUNITIES: List[Dict[str, Any]] = [
    {
        "slug": "aim-atal-tinkering-olympiad-2026",
        "title": "National Youth STEM & AI Innovation Challenge (2026)",
        "company_name": "Atal Innovation Mission / NITI Aayog",
        "role_category": "Student Competition",
        "required_skills": ["python", "problem-solving"],
        "preferred_skills": ["robotics", "creativity"],
        "min_experience_level": "Beginner / Student",
        "location_type": "Remote",
        "salary_range": "₹50,000 Cash Prize + Certificate",
        "description": "National innovation fellowship and competition for high school and secondary students to build applied AI solutions.",
        "opportunity_type": "Competition",
        "country": "India",
        "state": "All India",
        "city": "Pan-India",
        "min_education_stage": "School Education",
        "eligible_streams": ["Any", "Science", "General"],
        "application_url": "https://aim.gov.in/challenge-2026",
        "source": "NITI Aayog / JanSahay",
        "provider": "Government Initiative",
        "verification_status": "VERIFIED",
        "freshness": "FRESH"
    },
    {
        "slug": "aicte-student-summer-internship-2026",
        "title": "National Open Source & Cloud Apprentice",
        "company_name": "AICTE JanSahay Digital Hub",
        "role_category": "Software Engineer",
        "required_skills": ["python", "git", "linux"],
        "preferred_skills": ["docker", "web-development"],
        "min_experience_level": "Internship",
        "location_type": "Remote",
        "salary_range": "₹15,000 / month stipend",
        "description": "Government supported virtual technical apprenticeship contributing to public digital goods.",
        "opportunity_type": "Internship",
        "country": "India",
        "state": "Tamil Nadu",
        "city": "Chennai",
        "min_education_stage": "Higher Secondary",
        "eligible_streams": ["Science", "Computer Science", "Engineering"],
        "application_url": "https://internship.aicte-india.org/cloud-2026",
        "source": "AICTE Portal",
        "provider": "AICTE",
        "verification_status": "VERIFIED",
        "freshness": "FRESH"
    },
    {
        "slug": "intel-vlsi-bangalore-intern",
        "title": "Digital Design & VLSI Verification Intern",
        "company_name": "Intel India Technology",
        "role_category": "VLSI Hardware Engineer",
        "required_skills": ["digital-logic", "verilog"],
        "preferred_skills": ["systemverilog", "python"],
        "min_experience_level": "Internship",
        "location_type": "Onsite",
        "salary_range": "₹45,000 / month stipend",
        "description": "Verify next-generation low-power execution blocks using SystemVerilog testbenches in Bangalore labs.",
        "opportunity_type": "Internship",
        "country": "India",
        "state": "Karnataka",
        "city": "Bangalore",
        "min_education_stage": "Undergraduate",
        "eligible_streams": ["Electronics & Communication", "ECE", "Electrical", "VLSI"],
        "application_url": "https://jobs.intel.com/en/location/india-jobs",
        "source": "Intel Careers India",
        "provider": "Direct Employer",
        "verification_status": "VERIFIED",
        "freshness": "FRESH"
    },
    {
        "slug": "zoho-chennai-data-analyst",
        "title": "Junior Business Intelligence & Data Analyst",
        "company_name": "Zoho Corporation",
        "role_category": "Data Analyst",
        "required_skills": ["sql", "excel", "python"],
        "preferred_skills": ["tableau", "statistics"],
        "min_experience_level": "Entry Level",
        "location_type": "Hybrid",
        "salary_range": "₹5.5 LPA - ₹8 LPA",
        "description": "Analyze multi-tenant SaaS metrics, write high-performance SQL reports, and visualize growth telemetry.",
        "opportunity_type": "Full-Time",
        "country": "India",
        "state": "Tamil Nadu",
        "city": "Chennai",
        "min_education_stage": "Undergraduate",
        "eligible_streams": ["Commerce", "B.Com", "Computer Science", "Engineering", "Mathematics"],
        "application_url": "https://www.zoho.com/careers/data-analyst.html",
        "source": "Zoho Careers",
        "provider": "Direct Employer",
        "verification_status": "VERIFIED",
        "freshness": "FRESH"
    },
    {
        "slug": "swiggy-ml-engineer-bangalore",
        "title": "Associate Machine Learning & Recommendation Engineer",
        "company_name": "Swiggy",
        "role_category": "AI/ML Engineer",
        "required_skills": ["python", "deep-learning", "docker"],
        "preferred_skills": ["transformers", "sql"],
        "min_experience_level": "Entry Level",
        "location_type": "Hybrid",
        "salary_range": "₹12 LPA - ₹18 LPA",
        "description": "Develop and deploy scalable real-time neural ranking models for hyper-local delivery routing.",
        "opportunity_type": "Full-Time",
        "country": "India",
        "state": "Karnataka",
        "city": "Bangalore",
        "min_education_stage": "Undergraduate",
        "eligible_streams": ["Computer Science", "Engineering", "AI/ML", "Data Science"],
        "application_url": "https://careers.swiggy.com/ml-engineer",
        "source": "Swiggy Tech Careers",
        "provider": "Direct Employer",
        "verification_status": "VERIFIED",
        "freshness": "FRESH"
    },
    {
        "slug": "tcs-cyber-defense-hyderabad",
        "title": "Security Operations & Threat Defense Analyst",
        "company_name": "Tata Consultancy Services",
        "role_category": "Cybersecurity Analyst",
        "required_skills": ["networking", "linux", "web-security"],
        "preferred_skills": ["siem", "python"],
        "min_experience_level": "Entry Level",
        "location_type": "Onsite",
        "salary_range": "₹4.5 LPA - ₹7 LPA",
        "description": "Monitor 24/7 SOC telemetry, investigate security event anomalies, and automate intrusion containment scripts.",
        "opportunity_type": "Full-Time",
        "country": "India",
        "state": "Telangana",
        "city": "Hyderabad",
        "min_education_stage": "Undergraduate",
        "eligible_streams": ["Computer Science", "IT", "Cybersecurity", "Engineering"],
        "application_url": "https://www.tcs.com/careers/india-cyber-analyst",
        "source": "TCS NextStep Portal",
        "provider": "Direct Employer",
        "verification_status": "VERIFIED",
        "freshness": "FRESH"
    }
]
