from typing import Dict, List, Any, Optional
from datetime import datetime, timezone

PRICE_CATEGORIES = {
    "GENUINELY_FREE": "Learning content accessible without payment; no mandatory subscription or hidden fees",
    "FREE_TO_ENROLL_PAID_CERTIFICATE": "Learning content is free to access; verified credential/exam is optional and paid",
    "FREE_AUDIT_PAID_CERTIFICATE": "Audit access provided without charge; graded assignments and certificates require payment",
    "FREE_TRIAL": "Temporary time-bounded free trial; recurring subscription required afterward",
    "PAID": "Direct upfront purchase required for access",
    "SUBSCRIPTION_REQUIRED": "Platform-wide paid subscription required for access",
    "PARTIALLY_FREE": "Portion of modules free; advanced modules locked behind paywall",
    "UNKNOWN": "Pricing structure unverified or indeterminate",
    "YOUTUBE_FREE_CONTENT": "Publicly accessible educational video/playlist on YouTube without subscription"
}

RESOURCE_TYPES = [
    "course", "course_series", "youtube_video", "youtube_playlist", "lecture",
    "tutorial", "documentation", "book", "lab", "project", "certification",
    "practice_platform", "official_learning_path"
]

SUPPORTED_LANGUAGES = [
    "English", "Hindi", "Tamil", "Telugu", "Kannada", "Malayalam",
    "Marathi", "Bengali", "Gujarati", "Punjabi", "Odia", "Urdu"
]

SOURCE_TIERS = {
    1: "Official Government & University / Institutional (NPTEL, SWAYAM, IITs, Skill India)",
    2: "Official Tech-Provider Platforms (Microsoft Learn, Google Cloud, AWS, Cisco)",
    3: "Established Global EdTech Platforms (freeCodeCamp, MIT OCW, Coursera, edX)",
    4: "Curated YouTube Educational Content (Playlists & Deep-Dive Tutorials)"
}

# Verified Extended Resource Registry
EXTENDED_RESOURCES_REGISTRY: List[Dict[str, Any]] = [
    # Tier 1 - Institutional (NPTEL / SWAYAM / Skill India)
    {
        "id": "res-ext-nptel-py",
        "title": "Programming in Python (NPTEL / IIT Madras)",
        "slug": "nptel-programming-python",
        "provider": "NPTEL",
        "url": "https://nptel.ac.in/courses/106106182",
        "resource_type": "course",
        "difficulty": "Beginner",
        "estimated_hours": 30.0,
        "quality_score": 0.96,
        "career_relevance": ["ai-ml-engineer", "software-engineer", "data-scientist"],
        "format": "video",
        "language": "English",
        "skills": ["python"],
        "price_type": "FREE_TO_ENROLL_PAID_CERTIFICATE",
        "learning_cost": 0.0,
        "certificate_cost": "optional_paid",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": False,
        "verification_status": "VERIFIED",
        "verification_method": "institutional_api",
        "last_verified_at": datetime.now(timezone.utc),
        "source": "NPTEL National Portal",
        "source_tier": 1,
        "external_id": "NPTEL-106106182",
        "description": "Comprehensive semester-length university course covering procedural and object-oriented Python, algorithmic problem-solving, and computational data structures."
    },
    {
        "id": "res-ext-nptel-dl",
        "title": "Deep Learning (NPTEL / IIT Kharagpur)",
        "slug": "nptel-deep-learning-iitkgp",
        "provider": "NPTEL",
        "url": "https://nptel.ac.in/courses/106105215",
        "resource_type": "course",
        "difficulty": "Intermediate",
        "estimated_hours": 40.0,
        "quality_score": 0.95,
        "career_relevance": ["ai-ml-engineer", "data-scientist"],
        "format": "video",
        "language": "English",
        "skills": ["deep-learning", "transformers"],
        "price_type": "FREE_TO_ENROLL_PAID_CERTIFICATE",
        "learning_cost": 0.0,
        "certificate_cost": "optional_paid",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": False,
        "verification_status": "VERIFIED",
        "verification_method": "institutional_api",
        "last_verified_at": datetime.now(timezone.utc),
        "source": "NPTEL National Portal",
        "source_tier": 1,
        "external_id": "NPTEL-106105215",
        "description": "In-depth neural networks, backpropagation, CNN architectures, RNNs, and attention models taught by IIT faculty."
    },
    {
        "id": "res-ext-swayam-dbms",
        "title": "Database Management Systems (SWAYAM)",
        "slug": "swayam-dbms-iitb",
        "provider": "SWAYAM",
        "url": "https://swayam.gov.in/courses/dbms",
        "resource_type": "course",
        "difficulty": "Beginner",
        "estimated_hours": 25.0,
        "quality_score": 0.94,
        "career_relevance": ["data-scientist", "software-engineer"],
        "format": "video",
        "language": "English",
        "skills": ["sql"],
        "price_type": "FREE_TO_ENROLL_PAID_CERTIFICATE",
        "learning_cost": 0.0,
        "certificate_cost": "optional_paid",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": False,
        "verification_status": "VERIFIED",
        "verification_method": "institutional_api",
        "last_verified_at": datetime.now(timezone.utc),
        "source": "SWAYAM Government of India",
        "source_tier": 1,
        "external_id": "SWAYAM-DBMS-2026",
        "description": "Relational algebra, SQL query optimization, transaction management, and ACID guarantees."
    },

    # Tier 2 - Official Tech Providers (Genuinely Free Learning)
    {
        "id": "res-ext-msft-py",
        "title": "Python for Beginners (Microsoft Learn)",
        "slug": "microsoft-learn-python-beginners",
        "provider": "Microsoft Learn",
        "url": "https://learn.microsoft.com/en-us/training/paths/beginner-python/",
        "resource_type": "official_learning_path",
        "difficulty": "Beginner",
        "estimated_hours": 8.0,
        "quality_score": 0.93,
        "career_relevance": ["software-engineer", "ai-ml-engineer", "cloud-devops-engineer"],
        "format": "interactive",
        "language": "English",
        "skills": ["python"],
        "price_type": "GENUINELY_FREE",
        "learning_cost": 0.0,
        "certificate_cost": "free",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": True,
        "verification_status": "VERIFIED",
        "verification_method": "official_provider_api",
        "last_verified_at": datetime.now(timezone.utc),
        "source": "Microsoft Learn",
        "source_tier": 2,
        "external_id": "MSFT-LEARN-PY",
        "description": "Hands-on browser-based Python sandbox covering syntax, conditionals, functions, and error handling."
    },
    {
        "id": "res-ext-aws-cloud",
        "title": "AWS Cloud Practitioner Essentials",
        "slug": "aws-cloud-practitioner-essentials",
        "provider": "AWS Skill Builder",
        "url": "https://aws.amazon.com/training/digital/aws-cloud-practitioner-essentials/",
        "resource_type": "official_learning_path",
        "difficulty": "Beginner",
        "estimated_hours": 6.0,
        "quality_score": 0.94,
        "career_relevance": ["cloud-devops-engineer", "software-engineer"],
        "format": "video",
        "language": "English",
        "skills": ["docker", "kubernetes"],
        "price_type": "GENUINELY_FREE",
        "learning_cost": 0.0,
        "certificate_cost": "not_applicable",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": False,
        "verification_status": "VERIFIED",
        "verification_method": "official_provider_api",
        "last_verified_at": datetime.now(timezone.utc),
        "source": "AWS Skill Builder",
        "source_tier": 2,
        "external_id": "AWS-CP-FREE",
        "description": "Fundamental concepts of cloud computing, security, architecture, and deployment principles directly from AWS."
    },

    # Tier 3 - Established EdTech
    {
        "id": "res-ext-fcc-sql",
        "title": "Relational Database & SQL Certification (freeCodeCamp)",
        "slug": "freecodecamp-relational-database-sql",
        "provider": "freeCodeCamp",
        "url": "https://www.freecodecamp.org/learn/relational-database/",
        "resource_type": "practice_platform",
        "difficulty": "Beginner",
        "estimated_hours": 20.0,
        "quality_score": 0.95,
        "career_relevance": ["data-scientist", "software-engineer"],
        "format": "hands-on",
        "language": "English",
        "skills": ["sql"],
        "price_type": "GENUINELY_FREE",
        "learning_cost": 0.0,
        "certificate_cost": "free",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": True,
        "verification_status": "VERIFIED",
        "verification_method": "manual_curated",
        "last_verified_at": datetime.now(timezone.utc),
        "source": "freeCodeCamp",
        "source_tier": 3,
        "external_id": "FCC-RDBMS-2026",
        "description": "Interactive Linux container terminal environment learning PostgreSQL, Bash scripting, and SQL querying."
    },

    # Tier 4 - Curated YouTube Playlists (Language-Specific)
    {
        "id": "res-ext-yt-tamil-py",
        "title": "Complete Python Programming in Tamil (Full Course)",
        "slug": "python-programming-tamil-full-course",
        "provider": "Error Makes Clever Academy",
        "url": "https://www.youtube.com/watch?v=m67-bOpOoPU",
        "resource_type": "youtube_video",
        "difficulty": "Beginner",
        "estimated_hours": 12.0,
        "quality_score": 0.92,
        "career_relevance": ["ai-ml-engineer", "software-engineer", "data-scientist"],
        "format": "video",
        "language": "Tamil",
        "skills": ["python"],
        "price_type": "YOUTUBE_FREE_CONTENT",
        "learning_cost": 0.0,
        "certificate_cost": "not_applicable",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": False,
        "verification_status": "VERIFIED",
        "verification_method": "youtube_metadata",
        "last_verified_at": datetime.now(timezone.utc),
        "source": "YouTube India",
        "source_tier": 4,
        "external_id": "YT-TAMIL-PY-01",
        "description": "Comprehensive Tamil explanation of Python from installation to functions, OOP, and real-world project automation."
    },
    {
        "id": "res-ext-yt-tamil-sql",
        "title": "SQL Tutorial for Beginners in Tamil",
        "slug": "sql-tutorial-tamil-beginners",
        "provider": "Tech in Tamil",
        "url": "https://www.youtube.com/watch?v=7S_tz1z_5bA",
        "resource_type": "youtube_playlist",
        "difficulty": "Beginner",
        "estimated_hours": 8.0,
        "quality_score": 0.90,
        "career_relevance": ["data-scientist", "software-engineer"],
        "format": "video",
        "language": "Tamil",
        "skills": ["sql"],
        "price_type": "YOUTUBE_FREE_CONTENT",
        "learning_cost": 0.0,
        "certificate_cost": "not_applicable",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": False,
        "verification_status": "VERIFIED",
        "verification_method": "youtube_metadata",
        "last_verified_at": datetime.now(timezone.utc),
        "source": "YouTube India",
        "source_tier": 4,
        "external_id": "YT-TAMIL-SQL-01",
        "description": "Step-by-step SQL queries, joins, aggregates, and database normalization taught clearly in Tamil."
    },
    {
        "id": "res-ext-yt-hindi-py",
        "title": "Python for Beginners in Hindi (Complete Series)",
        "slug": "python-for-beginners-hindi-codewithharry",
        "provider": "CodeWithHarry",
        "url": "https://www.youtube.com/playlist?list=PLu0W_9lII9agwh1XjRt242xIpHhPT2llg",
        "resource_type": "youtube_playlist",
        "difficulty": "Beginner",
        "estimated_hours": 20.0,
        "quality_score": 0.93,
        "career_relevance": ["software-engineer", "ai-ml-engineer", "data-scientist"],
        "format": "video",
        "language": "Hindi",
        "skills": ["python"],
        "price_type": "YOUTUBE_FREE_CONTENT",
        "learning_cost": 0.0,
        "certificate_cost": "not_applicable",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": False,
        "verification_status": "VERIFIED",
        "verification_method": "youtube_metadata",
        "last_verified_at": datetime.now(timezone.utc),
        "source": "YouTube India",
        "source_tier": 4,
        "external_id": "YT-HINDI-PY-CWH",
        "description": "100 Days of Code Python series in Hindi covering fundamentals, data structures, and practical application building."
    },
    {
        "id": "res-ext-yt-telugu-py",
        "title": "Python Full Course in Telugu for Beginners",
        "slug": "python-full-course-telugu",
        "provider": "Kiran's Tech Telugu",
        "url": "https://www.youtube.com/watch?v=telugu_py_course",
        "resource_type": "youtube_video",
        "difficulty": "Beginner",
        "estimated_hours": 10.0,
        "quality_score": 0.89,
        "career_relevance": ["software-engineer", "data-scientist"],
        "format": "video",
        "language": "Telugu",
        "skills": ["python"],
        "price_type": "YOUTUBE_FREE_CONTENT",
        "learning_cost": 0.0,
        "certificate_cost": "not_applicable",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": False,
        "verification_status": "VERIFIED",
        "verification_method": "youtube_metadata",
        "last_verified_at": datetime.now(timezone.utc),
        "source": "YouTube India",
        "source_tier": 4,
        "external_id": "YT-TELUGU-PY-01",
        "description": "Clear Telugu language tutorial explaining core Python programming constructs, loops, and functions."
    },
    {
        "id": "res-ext-yt-eng-karpathy",
        "title": "Neural Networks: Zero to Hero (Andrej Karpathy)",
        "slug": "neural-networks-zero-to-hero-karpathy",
        "provider": "Andrej Karpathy",
        "url": "https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ",
        "resource_type": "youtube_playlist",
        "difficulty": "Intermediate",
        "estimated_hours": 15.0,
        "quality_score": 0.98,
        "career_relevance": ["ai-ml-engineer"],
        "format": "video",
        "language": "English",
        "skills": ["deep-learning", "transformers"],
        "price_type": "YOUTUBE_FREE_CONTENT",
        "learning_cost": 0.0,
        "certificate_cost": "not_applicable",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": False,
        "verification_status": "VERIFIED",
        "verification_method": "youtube_metadata",
        "last_verified_at": datetime.now(timezone.utc),
        "source": "YouTube",
        "source_tier": 4,
        "external_id": "YT-ENG-KARPATHY-01",
        "description": "Masterclass building micrograd, makemore, GPT-2 from scratch with PyTorch and pure mathematics."
    },
    {
        "id": "res-ext-yt-vlsi-verilog",
        "title": "Digital VLSI Design & Verilog HDL Series",
        "slug": "digital-vlsi-verilog-tutorial",
        "provider": "IIT Kharagpur / NPTEL YouTube",
        "url": "https://www.youtube.com/playlist?list=PLbRMhDVUMngfdZXb-4I0gP3p-K3Q8zM-x",
        "resource_type": "youtube_playlist",
        "difficulty": "Beginner",
        "estimated_hours": 18.0,
        "quality_score": 0.94,
        "career_relevance": ["vlsi-hardware-engineer"],
        "format": "video",
        "language": "English",
        "skills": ["digital-logic"],
        "price_type": "YOUTUBE_FREE_CONTENT",
        "learning_cost": 0.0,
        "certificate_cost": "not_applicable",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": False,
        "verification_status": "VERIFIED",
        "verification_method": "youtube_metadata",
        "last_verified_at": datetime.now(timezone.utc),
        "source": "YouTube India",
        "source_tier": 4,
        "external_id": "YT-VLSI-01",
        "description": "RTL modeling, state machine synthesis, testbench generation, and digital simulation."
    },

    # =========================================================================
    # Tier 1 - Government Learning Platforms: iGOT Karmayogi (Govt of India)
    # =========================================================================
    {
        "id": "res-igot-data-decision",
        "title": "Data Driven Decision Making For Government",
        "slug": "igot-data-driven-decision-making-government",
        "provider": "iGOT Karmayogi",
        "provider_id": "igot_karmayogi",
        "source_platform": "IGOT",
        "source_tier": 1,
        "url": "https://portal.igotkarmayogi.gov.in/app/toc/lex_auth_013759281920381000",
        "canonical_url": "https://portal.igotkarmayogi.gov.in/app/toc/lex_auth_013759281920381000",
        "resource_type": "course",
        "difficulty": "Beginner",
        "estimated_hours": 3.5,
        "quality_score": 0.96,
        "career_relevance": ["public-administration", "public-policy", "data-analytics", "governance", "business-analyst"],
        "format": "interactive",
        "language": "English",
        "skills": ["data-analysis", "decision-making", "data-literacy"],
        "competencies": ["Data Driven Decision Making", "Data Literacy", "Public Policy Writing"],
        "topics": ["Evidence-based Policy", "Data Interpretation", "Government Analytics"],
        "price_type": "GENUINELY_FREE",
        "learning_cost": 0.0,
        "certificate_cost": "free",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": True,
        "verification_status": "VERIFIED",
        "verification_method": "official_public_registry",
        "last_verified_at": datetime.now(timezone.utc),
        "retrieved_at": datetime.now(timezone.utc),
        "freshness": "FRESH",
        "source": "iGOT Karmayogi Official Portal",
        "external_id": "IGOT-GOV-DATA-DECISION-01",
        "description": "Evidence-based policy formulation, data visualization, governance telemetry, and quantitative decision matrices for modern public sector leadership.",
        "why_recommended": "Official Government of India curriculum building essential quantitative and evidence-driven decision-making competencies."
    },
    {
        "id": "res-igot-public-policy",
        "title": "Fundamentals of Public Policy",
        "slug": "igot-fundamentals-of-public-policy",
        "provider": "iGOT Karmayogi",
        "provider_id": "igot_karmayogi",
        "source_platform": "IGOT",
        "source_tier": 1,
        "url": "https://portal.igotkarmayogi.gov.in/app/toc/lex_auth_013849120491028300",
        "canonical_url": "https://portal.igotkarmayogi.gov.in/app/toc/lex_auth_013849120491028300",
        "resource_type": "course",
        "difficulty": "Intermediate",
        "estimated_hours": 6.0,
        "quality_score": 0.95,
        "career_relevance": ["public-policy", "public-administration", "governance", "legal-compliance"],
        "format": "interactive",
        "language": "English",
        "skills": ["public-policy", "policy-analysis", "governance"],
        "competencies": ["Fundamentals of Public Policy", "Public Policy Writing", "Governance"],
        "topics": ["Policy Formulation", "Legislative Drafting", "Implementation Monitoring"],
        "price_type": "GENUINELY_FREE",
        "learning_cost": 0.0,
        "certificate_cost": "free",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": True,
        "verification_status": "VERIFIED",
        "verification_method": "official_public_registry",
        "last_verified_at": datetime.now(timezone.utc),
        "retrieved_at": datetime.now(timezone.utc),
        "freshness": "FRESH",
        "source": "iGOT Karmayogi Official Portal",
        "external_id": "IGOT-GOV-PUBLIC-POLICY-02",
        "description": "Comprehensive framework covering policy cycles, stakeholder consultation, constitutional provisions, regulatory impact, and implementation metrics in India.",
        "why_recommended": "Authoritative foundation for public administration and governance careers."
    },
    {
        "id": "res-igot-genai-bard",
        "title": "AI Using Google Bard and ChatGPT for Beginners",
        "slug": "igot-ai-using-google-bard-chatgpt-beginners",
        "provider": "iGOT Karmayogi",
        "provider_id": "igot_karmayogi",
        "source_platform": "IGOT",
        "source_tier": 1,
        "url": "https://portal.igotkarmayogi.gov.in/app/toc/lex_auth_013910284910293000",
        "canonical_url": "https://portal.igotkarmayogi.gov.in/app/toc/lex_auth_013910284910293000",
        "resource_type": "course",
        "difficulty": "Beginner",
        "estimated_hours": 2.5,
        "quality_score": 0.94,
        "career_relevance": ["ai-ml-engineer", "software-engineer", "public-administration", "product-management"],
        "format": "interactive",
        "language": "English",
        "skills": ["generative-ai", "prompt-engineering", "llms"],
        "competencies": ["AI Using Google Bard and ChatGPT", "Prompt Engineering"],
        "topics": ["Large Language Models", "Productivity Automation", "AI Ethics"],
        "price_type": "GENUINELY_FREE",
        "learning_cost": 0.0,
        "certificate_cost": "free",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": True,
        "verification_status": "VERIFIED",
        "verification_method": "official_public_registry",
        "last_verified_at": datetime.now(timezone.utc),
        "retrieved_at": datetime.now(timezone.utc),
        "freshness": "FRESH",
        "source": "iGOT Karmayogi Official Portal",
        "external_id": "IGOT-TECH-AI-BARD-03",
        "description": "Practical generative AI productivity primer covering prompt engineering, workplace automation, ethical AI usage, and synthetic content validation.",
        "why_recommended": "Teaches fundamental generative AI and prompt design principles recognized in official government programs."
    },
    {
        "id": "res-igot-digital-safety",
        "title": "Digital Safety Essentials",
        "slug": "igot-digital-safety-essentials",
        "provider": "iGOT Karmayogi",
        "provider_id": "igot_karmayogi",
        "source_platform": "IGOT",
        "source_tier": 1,
        "url": "https://portal.igotkarmayogi.gov.in/app/toc/lex_auth_013692849102948100",
        "canonical_url": "https://portal.igotkarmayogi.gov.in/app/toc/lex_auth_013692849102948100",
        "resource_type": "course",
        "difficulty": "Beginner",
        "estimated_hours": 2.0,
        "quality_score": 0.93,
        "career_relevance": ["cybersecurity", "software-engineer", "public-administration"],
        "format": "interactive",
        "language": "English",
        "skills": ["cybersecurity", "information-security"],
        "competencies": ["Digital Safety Essentials", "Cyber Security"],
        "topics": ["Phishing Defense", "Credential Hygiene", "Information Security"],
        "price_type": "GENUINELY_FREE",
        "learning_cost": 0.0,
        "certificate_cost": "free",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": True,
        "verification_status": "VERIFIED",
        "verification_method": "official_public_registry",
        "last_verified_at": datetime.now(timezone.utc),
        "retrieved_at": datetime.now(timezone.utc),
        "freshness": "FRESH",
        "source": "iGOT Karmayogi Official Portal",
        "external_id": "IGOT-SEC-DIGITAL-SAFETY-04",
        "description": "National cybersecurity and privacy awareness course: phishing defense, secure authentication, CERT-In compliance guidelines, and data protection.",
        "why_recommended": "Directly develops digital security and compliance readiness aligned with national information security standards."
    },
    {
        "id": "res-igot-admin-law",
        "title": "Basics of Administrative Law",
        "slug": "igot-basics-of-administrative-law",
        "provider": "iGOT Karmayogi",
        "provider_id": "igot_karmayogi",
        "source_platform": "IGOT",
        "source_tier": 1,
        "url": "https://portal.igotkarmayogi.gov.in/app/toc/lex_auth_013789204910294800",
        "canonical_url": "https://portal.igotkarmayogi.gov.in/app/toc/lex_auth_013789204910294800",
        "resource_type": "course",
        "difficulty": "Intermediate",
        "estimated_hours": 5.0,
        "quality_score": 0.95,
        "career_relevance": ["public-administration", "law", "public-policy", "legal-compliance"],
        "format": "interactive",
        "language": "English",
        "skills": ["administrative-law", "governance", "legal-compliance"],
        "competencies": ["Basics of Administrative Law", "Governance"],
        "topics": ["Natural Justice", "Quasi-Judicial Powers", "Constitutional Law"],
        "price_type": "GENUINELY_FREE",
        "learning_cost": 0.0,
        "certificate_cost": "free",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": True,
        "verification_status": "VERIFIED",
        "verification_method": "official_public_registry",
        "last_verified_at": datetime.now(timezone.utc),
        "retrieved_at": datetime.now(timezone.utc),
        "freshness": "FRESH",
        "source": "iGOT Karmayogi Official Portal",
        "external_id": "IGOT-LAW-ADMIN-08",
        "description": "Constitutional principles, natural justice, delegated legislation, administrative tribunals, and judicial review mechanisms in the Indian legal framework.",
        "why_recommended": "Core legal literacy for public governance and regulatory oversight."
    },
    {
        "id": "res-igot-egov",
        "title": "E-Governance and Digital Transformation",
        "slug": "igot-e-governance-digital-transformation",
        "provider": "iGOT Karmayogi",
        "provider_id": "igot_karmayogi",
        "source_platform": "IGOT",
        "source_tier": 1,
        "url": "https://portal.igotkarmayogi.gov.in/app/toc/lex_auth_013990284910293800",
        "canonical_url": "https://portal.igotkarmayogi.gov.in/app/toc/lex_auth_013990284910293800",
        "resource_type": "course",
        "difficulty": "Intermediate",
        "estimated_hours": 4.5,
        "quality_score": 0.96,
        "career_relevance": ["public-administration", "software-engineer", "cybersecurity", "product-management"],
        "format": "interactive",
        "language": "English",
        "skills": ["e-governance", "digital-governance", "public-administration"],
        "competencies": ["E-Governance and Digital Transformation", "Digital Governance"],
        "topics": ["India Stack", "API Integration", "Citizen Security"],
        "price_type": "GENUINELY_FREE",
        "learning_cost": 0.0,
        "certificate_cost": "free",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": True,
        "verification_status": "VERIFIED",
        "verification_method": "official_public_registry",
        "last_verified_at": datetime.now(timezone.utc),
        "retrieved_at": datetime.now(timezone.utc),
        "freshness": "FRESH",
        "source": "iGOT Karmayogi Official Portal",
        "external_id": "IGOT-GOV-EGOV-09",
        "description": "Architecture of India Stack, DigiLocker, Aadhaar authentication, interoperability frameworks, and secure digital service delivery.",
        "why_recommended": "Comprehensive study of national digital public infrastructure."
    },

    # =========================================================================
    # Tier 2 - Official Technology Providers: Microsoft, Google, AWS, Cisco, IBM
    # =========================================================================
    {
        "id": "res-ms-azure-fund",
        "title": "Microsoft Azure Fundamentals (AZ-900)",
        "slug": "microsoft-azure-fundamentals-az900",
        "provider": "Microsoft Learn",
        "provider_id": "microsoft_learn",
        "source_platform": "MICROSOFT_LEARN",
        "source_tier": 2,
        "url": "https://learn.microsoft.com/training/paths/azure-fundamentals/",
        "canonical_url": "https://learn.microsoft.com/training/paths/azure-fundamentals/",
        "resource_type": "course",
        "difficulty": "Beginner",
        "estimated_hours": 12.0,
        "quality_score": 0.97,
        "career_relevance": ["cloud-engineer", "devops-engineer", "software-engineer"],
        "format": "interactive",
        "language": "English",
        "skills": ["cloud-computing", "azure"],
        "price_type": "GENUINELY_FREE",
        "learning_cost": 0.0,
        "certificate_cost": "optional_paid",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": False,
        "verification_status": "VERIFIED",
        "verification_method": "official_tech_catalog",
        "last_verified_at": datetime.now(timezone.utc),
        "retrieved_at": datetime.now(timezone.utc),
        "freshness": "FRESH",
        "source": "Microsoft Learn Official",
        "external_id": "MS-AZ900-PATH",
        "description": "Cloud concepts, Azure architecture and services, and Azure management and governance directly from Microsoft.",
        "why_recommended": "Official Microsoft certification pathway for cloud computing fundamentals."
    },
    {
        "id": "res-ms-ai-fund",
        "title": "Microsoft Azure AI Fundamentals (AI-900)",
        "slug": "microsoft-azure-ai-fundamentals-ai900",
        "provider": "Microsoft Learn",
        "provider_id": "microsoft_learn",
        "source_platform": "MICROSOFT_LEARN",
        "source_tier": 2,
        "url": "https://learn.microsoft.com/training/paths/get-started-with-artificial-intelligence-on-azure/",
        "canonical_url": "https://learn.microsoft.com/training/paths/get-started-with-artificial-intelligence-on-azure/",
        "resource_type": "course",
        "difficulty": "Beginner",
        "estimated_hours": 10.0,
        "quality_score": 0.96,
        "career_relevance": ["ai-ml-engineer", "data-scientist"],
        "format": "interactive",
        "language": "English",
        "skills": ["ai-fundamentals", "computer-vision", "nlp", "generative-ai"],
        "price_type": "GENUINELY_FREE",
        "learning_cost": 0.0,
        "certificate_cost": "optional_paid",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": False,
        "verification_status": "VERIFIED",
        "verification_method": "official_tech_catalog",
        "last_verified_at": datetime.now(timezone.utc),
        "retrieved_at": datetime.now(timezone.utc),
        "freshness": "FRESH",
        "source": "Microsoft Learn Official",
        "external_id": "MS-AI900-PATH",
        "description": "Foundational knowledge of machine learning and artificial intelligence concepts and related Microsoft Azure services.",
        "why_recommended": "Direct vendor training on computer vision, natural language processing, and conversational AI."
    },
    {
        "id": "res-google-ml-crash",
        "title": "Machine Learning Crash Course (Google Developers)",
        "slug": "google-machine-learning-crash-course",
        "provider": "Google",
        "provider_id": "google_cloud",
        "source_platform": "GOOGLE",
        "source_tier": 2,
        "url": "https://developers.google.com/machine-learning/crash-course",
        "canonical_url": "https://developers.google.com/machine-learning/crash-course",
        "resource_type": "course",
        "difficulty": "Intermediate",
        "estimated_hours": 15.0,
        "quality_score": 0.98,
        "career_relevance": ["ai-ml-engineer", "data-scientist", "data-engineer"],
        "format": "interactive",
        "language": "English",
        "skills": ["machine-learning", "python", "neural-networks"],
        "price_type": "GENUINELY_FREE",
        "learning_cost": 0.0,
        "certificate_cost": "not_applicable",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": False,
        "verification_status": "VERIFIED",
        "verification_method": "official_tech_catalog",
        "last_verified_at": datetime.now(timezone.utc),
        "retrieved_at": datetime.now(timezone.utc),
        "freshness": "FRESH",
        "source": "Google Developers Official",
        "external_id": "GOOGLE-MLCC-01",
        "description": "Google's fast-paced, practical introduction to machine learning featuring a series of video lectures, real-world case studies, and hands-on practice exercises.",
        "why_recommended": "World-class engineering curriculum authored by Google research scientists."
    },
    {
        "id": "res-aws-cloud-prac",
        "title": "AWS Cloud Practitioner Essentials",
        "slug": "aws-cloud-practitioner-essentials",
        "provider": "AWS",
        "provider_id": "aws_training",
        "source_platform": "AWS",
        "source_tier": 2,
        "url": "https://explore.skillbuilder.aws/learn/course/external/view/elearning/134/aws-cloud-practitioner-essentials",
        "canonical_url": "https://explore.skillbuilder.aws/learn/course/external/view/elearning/134/aws-cloud-practitioner-essentials",
        "resource_type": "course",
        "difficulty": "Beginner",
        "estimated_hours": 6.0,
        "quality_score": 0.96,
        "career_relevance": ["cloud-engineer", "devops-engineer", "software-engineer"],
        "format": "interactive",
        "language": "English",
        "skills": ["cloud-computing", "aws"],
        "price_type": "GENUINELY_FREE",
        "learning_cost": 0.0,
        "certificate_cost": "optional_paid",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": False,
        "verification_status": "VERIFIED",
        "verification_method": "official_tech_catalog",
        "last_verified_at": datetime.now(timezone.utc),
        "retrieved_at": datetime.now(timezone.utc),
        "freshness": "FRESH",
        "source": "AWS Skill Builder Official",
        "external_id": "AWS-CLP-01",
        "description": "Fundamental AWS Cloud concepts including security, architecture, pricing, and support to build AWS cloud knowledge.",
        "why_recommended": "Official Amazon Web Services training curriculum."
    },
    {
        "id": "res-cisco-net-basics",
        "title": "Networking Basics (Cisco Skills for All)",
        "slug": "cisco-networking-basics",
        "provider": "Cisco",
        "provider_id": "cisco_networking_academy",
        "source_platform": "CISCO",
        "source_tier": 2,
        "url": "https://www.skillsforall.com/course/networking-basics",
        "canonical_url": "https://www.skillsforall.com/course/networking-basics",
        "resource_type": "course",
        "difficulty": "Beginner",
        "estimated_hours": 25.0,
        "quality_score": 0.95,
        "career_relevance": ["network-engineer", "devops-engineer", "cybersecurity"],
        "format": "interactive",
        "language": "English",
        "skills": ["computer-networks", "tcp-ip"],
        "price_type": "GENUINELY_FREE",
        "learning_cost": 0.0,
        "certificate_cost": "free",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": True,
        "verification_status": "VERIFIED",
        "verification_method": "official_tech_catalog",
        "last_verified_at": datetime.now(timezone.utc),
        "retrieved_at": datetime.now(timezone.utc),
        "freshness": "FRESH",
        "source": "Cisco Networking Academy",
        "external_id": "CISCO-NET-01",
        "description": "Learn the fundamentals of computer networking, IP addressing, protocols, and network devices with Cisco packet tracer labs.",
        "why_recommended": "Authoritative industry-standard networking training directly from Cisco."
    },
    {
        "id": "res-ibm-data-science",
        "title": "Data Science Fundamentals (IBM SkillsBuild)",
        "slug": "ibm-data-science-fundamentals",
        "provider": "IBM",
        "provider_id": "ibm_skillsbuild",
        "source_platform": "IBM",
        "source_tier": 2,
        "url": "https://skillsbuild.org/students/course/data-science-fundamentals",
        "canonical_url": "https://skillsbuild.org/students/course/data-science-fundamentals",
        "resource_type": "course",
        "difficulty": "Beginner",
        "estimated_hours": 14.0,
        "quality_score": 0.94,
        "career_relevance": ["data-scientist", "data-analytics", "ai-ml-engineer"],
        "format": "interactive",
        "language": "English",
        "skills": ["data-science", "python", "data-analysis"],
        "price_type": "GENUINELY_FREE",
        "learning_cost": 0.0,
        "certificate_cost": "free",
        "subscription_required": False,
        "free_learning": True,
        "free_certificate": True,
        "verification_status": "VERIFIED",
        "verification_method": "official_tech_catalog",
        "last_verified_at": datetime.now(timezone.utc),
        "retrieved_at": datetime.now(timezone.utc),
        "freshness": "FRESH",
        "source": "IBM SkillsBuild Official",
        "external_id": "IBM-DS-01",
        "description": "Explore data science methodologies, statistical analysis, and open-source data science tools with hands-on lab modules.",
        "why_recommended": "Industry credential program provided free of charge by IBM."
    }
]

